version: "3.0"

services:
    arthur-monitor:
        image: eduartrobotik/eduart-robot-control:0.3.3
        container_name: arthur-monitor-0.3.3
        user: user
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=${EDU_ROBOT_NAMESPACE}
            - DISPLAY
        network_mode: "host"
        command: bash -c "cd /home/user/ros/launch_content; ros2 launch arthur_monitor.launch.py"
        devices:
            - '/dev:/dev'
        volumes:
            - '/dev:/dev'
            - './launch_content:/home/user/ros/launch_content:r'
            - '/tmp/.X11-unix:/tmp/.X11-unix:rw'
