version: "3.0"

services:
    eduard-robot-control:
        image: eduartrobotik/eduard-robot-control-iotbot:0.3.1
        container_name: eduard-robot-control-iotbot-0.3.1
        user: root
        restart: always
        privileged: true
        ipc: host
        pid: host
        mem_limit: 300mb
        environment:
            - EDU_ROBOT_NAMESPACE=eduard/red
        network_mode: "host"
        devices:
            - '/dev:/dev'
        volumes:
            - '/dev:/dev'
